//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto
{
    using System;
    using System.Collections.Generic;
    
    public partial class StandardGame : Game
    {
    
        public virtual StandardToutnament Toutnament { get; set; }
        public virtual Player PlayerOne { get; set; }
        public virtual Player PlayerTwo { get; set; }
    }
}
